In [2]:
## updated file with changs in train test split sequences
import pandas as pd
messages=pd.read_csv('/home/manan/jypyternotebook/NLP/spam.csv',  skiprows=[0], usecols=[0, 1], names=["label","message"])


In [3]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will �_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [4]:
## Data cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ', messages['message'][i])
    review=review.lower()
    review=review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Create BOW

In [8]:
## Output features
Y=pd.get_dummies(messages['label']).astype(int)
Y=Y.iloc[:, 1].values
Y

array([0, 0, 1, ..., 0, 0, 0])

In [9]:
## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(corpus,Y,test_size=0.20)

In [10]:
## Create Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
## for binary BOW, enable binary=true
cv=CountVectorizer(max_features=2500, ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
X_test=cv.transform(X_test).toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))

In [15]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [11]:
cv.vocabulary_

{'go': 801,
 'point': 1605,
 'crazi': 452,
 'avail': 123,
 'bugi': 230,
 'great': 855,
 'world': 2430,
 'la': 1084,
 'cine': 349,
 'got': 843,
 'wat': 2338,
 'ok': 1472,
 'lar': 1096,
 'joke': 1051,
 'wif': 2395,
 'free': 723,
 'entri': 617,
 'wkli': 2419,
 'comp': 400,
 'win': 2400,
 'fa': 653,
 'cup': 466,
 'final': 688,
 'st': 1961,
 'may': 1265,
 'text': 2074,
 'receiv': 1699,
 'question': 1664,
 'std': 1976,
 'txt': 2203,
 'rate': 1679,
 'appli': 86,
 'free entri': 728,
 'entri wkli': 619,
 'std txt': 1977,
 'txt rate': 2209,
 'rate appli': 1680,
 'dun': 577,
 'say': 1795,
 'earli': 583,
 'alreadi': 55,
 'nah': 1386,
 'think': 2100,
 'goe': 823,
 'usf': 2273,
 'live': 1163,
 'around': 99,
 'though': 2110,
 'freemsg': 735,
 'hey': 921,
 'darl': 483,
 'week': 2363,
 'word': 2425,
 'back': 140,
 'like': 1148,
 'fun': 755,
 'still': 1979,
 'tb': 2052,
 'xxx': 2465,
 'send': 1826,
 'even': 627,
 'brother': 220,
 'speak': 1942,
 'treat': 2178,
 'per': 1543,
 'request': 1733,
 'mell': 12

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
spam_detect_model=MultinomialNB().fit(X_train,Y_train)

In [19]:
Y.ndim # to check if it is numpy array ndim == 1

1

In [20]:
Y_pred=spam_detect_model.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, accuracy_score

In [22]:
accuracy_score(Y_test,Y_pred)

0.9838565022421525

In [23]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.96      0.92      0.94       156

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



## Create TF-Idf Model

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tv=TfidfVectorizer(max_features=2500, ngram_range=(1,2))

In [32]:
## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(corpus,Y,test_size=0.20)

In [33]:
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [34]:
tv.vocabulary_

{'place': 1568,
 'get': 775,
 'room': 1753,
 'cheap': 317,
 'much': 1361,
 'tri': 2181,
 'tri get': 2183,
 'sir': 1882,
 'cool': 415,
 'fun': 751,
 'practic': 1614,
 'make': 1229,
 'babi': 127,
 'time': 2131,
 'tonight': 2163,
 'whenev': 2392,
 'text': 2081,
 'around': 89,
 'cool text': 416,
 'yeah': 2478,
 'probabl': 1635,
 'still': 1977,
 'gotta': 848,
 'check': 319,
 'yeah probabl': 2480,
 'discuss': 533,
 'mother': 1344,
 'ah': 28,
 'told': 2151,
 'dat': 472,
 'face': 646,
 'watch': 2350,
 'realli': 1685,
 'like': 1154,
 'gave': 763,
 'co': 353,
 'fr': 714,
 'thanx': 2100,
 'everyth': 628,
 'done': 546,
 'today': 2146,
 'touch': 2170,
 'dear': 487,
 'leav': 1129,
 'qatar': 1651,
 'opportun': 1491,
 'pl': 1562,
 'keep': 1068,
 'lt': 1210,
 'email': 591,
 'gt': 864,
 'kerala': 1072,
 'keep touch': 1070,
 'cours': 426,
 'guess': 884,
 'god': 820,
 'got': 842,
 'hold': 943,
 'right': 1740,
 'best': 159,
 'say': 1790,
 'caus': 297,
 'man': 1236,
 'nice': 1413,
 'air': 35,
 'opinion': 14

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
spam_tfidf=MultinomialNB().fit(X_train,Y_train)

In [36]:
## pred
y_pred=spam_tfidf.predict(X_test)

In [37]:
score=accuracy_score(Y_test,y_pred)

In [38]:
print(score)

0.979372197309417


In [39]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       974
           1       0.99      0.84      0.91       141

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

