In [0]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [0]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king=wv['king']

In [0]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [0]:
##import pandas as pd
## messages=pd.read_csv('/home/manan/jypyternotebook/NLP/spam.csv',  skiprows=[0], usecols=[0, 1], names=["label","message"])
import pandas as pd
messages=pd.read_csv('/home/manan/jypyternotebook/NLP/SMSSpamCollection.csv',
                    sep='\t',names=["label","message"])
messages.shape

(5572, 2)

In [0]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [0]:
type(messages)

pandas.core.frame.DataFrame

In [0]:
from nltk.stem import WordNetLemmatizer
lemmitizer=WordNetLemmatizer()

In [0]:
## Data cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')
import re
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ', messages['message'][i])
# Uses regex to replace all non-alphabetic characters (numbers, symbols, etc.) with a space.
# Example: "Hello! 123 World." → "Hello World "
    review=review.lower()
    review=review.split()
    review = [lemmitizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)    
# Example Input → Output
# Input Message (raw):
# "Hey! I'm learning NLP. It's awesome! 123."
# Processed Output in corpus:
# "hey i m learning nlp it s awesome"

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [0]:
len(corpus)

5572

In [0]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [0]:
words=[]

In [0]:
# aletnative to using the above method to make corpus lowercae and splitting
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [0]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [0]:
import gensim
## lets train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [0]:
# to get all the vocabulory 
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [0]:
model.corpus_count

5569

In [0]:
model.epochs

5

In [0]:
model.wv.similar_by_word('world')

[('amp', 0.9991376399993896),
 ('try', 0.9990841746330261),
 ('had', 0.9990771412849426),
 ('getting', 0.999056875705719),
 ('also', 0.9990283250808716),
 ('never', 0.9990113377571106),
 ('any', 0.9989559054374695),
 ('an', 0.9989525675773621),
 ('special', 0.9989339709281921),
 ('down', 0.9989302754402161)]

## Average word2vec

In [0]:
!pip install tqdm
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [0]:
from tqdm import tqdm

In [0]:
# apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|                                                                                                                                           | 0/5569 [00:00<?, ?it/s]/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.9/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 7921.45it/s]


In [0]:
X[450]

array([-0.18751319,  0.38437125,  0.168372  ,  0.11002669,  0.07900354,
       -0.73157763,  0.28670126,  0.65446186, -0.34311163, -0.21106246,
       -0.20599264, -0.5188846 , -0.08682933,  0.12937662,  0.27248624,
       -0.22920084,  0.11182913, -0.4192069 , -0.12637167, -0.68861777,
        0.2635674 ,  0.11027539,  0.05307612, -0.33319676, -0.04347948,
       -0.07367431, -0.27235737, -0.25032097, -0.41294843,  0.01419551,
        0.40362525,  0.04132417,  0.1961751 , -0.33161217, -0.14541897,
        0.5360857 ,  0.1617359 , -0.18045297, -0.24038365, -0.65739554,
        0.08995543, -0.34065026, -0.28816286, -0.02824577,  0.21546614,
       -0.01388353, -0.10309548, -0.02931098,  0.36457407,  0.21639416,
        0.21023881, -0.30103582, -0.10961856,  0.0845442 , -0.07523652,
        0.07676841,  0.18665543, -0.02615384, -0.49489856,  0.23601684,
        0.01705114,  0.20495746,  0.01352757, -0.18840982, -0.41766465,
        0.42177886,  0.13152635,  0.30126956, -0.5292545 ,  0.57

In [0]:
len(X)

5569

In [0]:
X_new=np.array(X, dtype=object)

In [0]:
X_new.shape

(5569,)

In [0]:
# we are getting average vector for single sentence
X_new[1]

array([-0.1700153 ,  0.20970194,  0.10954425,  0.07233903,  0.08881661,
       -0.43763036,  0.14330038,  0.4125686 , -0.2335692 , -0.10773189,
       -0.14644252, -0.32201907, -0.04162646,  0.08328705,  0.18125865,
       -0.15792729,  0.09543346, -0.28045887, -0.08078097, -0.46088725,
        0.18118227,  0.08266522,  0.05934974, -0.18287195, -0.04085323,
       -0.02340822, -0.17146555, -0.18072721, -0.23831767,  0.02929103,
        0.27077216,  0.00903323,  0.08337114, -0.16369168, -0.09869926,
        0.33705318,  0.05463983, -0.10583407, -0.10879229, -0.41268054,
        0.09354433, -0.19433385, -0.1575704 , -0.00605849,  0.11954768,
        0.00744681, -0.0939157 , -0.02654343,  0.18356109,  0.1261537 ,
        0.12803265, -0.1689134 , -0.03015217,  0.05620223, -0.03404272,
        0.06853318,  0.13421753,  0.00413301, -0.30961284,  0.16428222,
        0.01523332,  0.13603312,  0.0098696 , -0.08327695, -0.26393488,
        0.22347149,  0.08401422,  0.19348073, -0.2976833 ,  0.34

In [0]:
X_new[1].shape


(100,)

In [0]:
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [0]:
## Dependent Features
## Output Features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
# get_dummies do a one hot encoding to a multi category column
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].astype(int).values

In [0]:
y.shape

(5569,)

In [0]:
X[0].reshape(1,-1).shape

(1, 100)

In [0]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [0]:
# now we see 3 records are lost, 5569 was coming as the amount of records available
messages.shape

(5572, 2)

In [0]:
## this is the final independent features
df=pd.DataFrame()
# dfs = []
# for i in range(0,len(X)):
#     df=df.concat(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)

dfs = []

for i in range(0,len(X)):
    # Reshape X[i] and convert to DataFrame
    df_row = pd.DataFrame(X[i].reshape(1, -1))
    dfs.append(df_row)

# Concatenate all DataFrames at once
df = pd.concat(dfs, ignore_index=True)

/tmp/ipykernel_5409/1665882813.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(dfs, ignore_index=True)


In [0]:
df.head()


,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.177414,0.237393,0.125967,0.082470,0.091033,-0.498894,0.178715,0.465901,-0.263933,-0.133093,...,0.365237,0.146224,0.044420,0.050784,0.434386,0.192929,0.136326,-0.213253,0.159961,-0.002274
1,-0.170015,0.209702,0.109544,0.072339,0.088817,-0.437630,0.143300,0.412569,-0.233569,-0.107732,...,0.328229,0.120417,0.033256,0.038274,0.371053,0.166493,0.121134,-0.197387,0.145468,-0.008423
2,-0.188137,0.251908,0.130214,0.093027,0.071000,-0.541898,0.181960,0.460621,-0.271368,-0.159701,...,0.353331,0.148207,0.037632,0.029104,0.446971,0.182839,0.090693,-0.242668,0.186581,0.019225
3,-0.244734,0.321940,0.165683,0.114463,0.123399,-0.665596,0.234085,0.630801,-0.361202,-0.170709,...,0.496381,0.192552,0.058199,0.077179,0.573833,0.264703,0.202165,-0.288419,0.214201,-0.014463
4,-0.216642,0.271278,0.150884,0.097256,0.113703,-0.574168,0.200820,0.550504,-0.313991,-0.156661,...,0.429884,0.163364,0.053190,0.066717,0.498476,0.230226,0.164305,-0.259953,0.182173,-0.012112


In [0]:
## reshape logic
X[1]


array([-0.1700153 ,  0.20970194,  0.10954425,  0.07233903,  0.08881661,
       -0.43763036,  0.14330038,  0.4125686 , -0.2335692 , -0.10773189,
       -0.14644252, -0.32201907, -0.04162646,  0.08328705,  0.18125865,
       -0.15792729,  0.09543346, -0.28045887, -0.08078097, -0.46088725,
        0.18118227,  0.08266522,  0.05934974, -0.18287195, -0.04085323,
       -0.02340822, -0.17146555, -0.18072721, -0.23831767,  0.02929103,
        0.27077216,  0.00903323,  0.08337114, -0.16369168, -0.09869926,
        0.33705318,  0.05463983, -0.10583407, -0.10879229, -0.41268054,
        0.09354433, -0.19433385, -0.1575704 , -0.00605849,  0.11954768,
        0.00744681, -0.0939157 , -0.02654343,  0.18356109,  0.1261537 ,
        0.12803265, -0.1689134 , -0.03015217,  0.05620223, -0.03404272,
        0.06853318,  0.13421753,  0.00413301, -0.30961284,  0.16428222,
        0.01523332,  0.13603312,  0.0098696 , -0.08327695, -0.26393488,
        0.22347149,  0.08401422,  0.19348073, -0.2976833 ,  0.34

In [0]:
X[1].reshape(1,-1).shape
## reshape converted a column with multiple rows to a row with multiple columns.

(1, 100)

In [0]:
df.shape

(5569, 100)

In [0]:
## Independent feature
X = df

In [0]:
## train test split
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y, test_size=0.20)

In [0]:
 Y_train

array([0, 1, 0, ..., 0, 1, 1])

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
classifier=RandomForestClassifier()
classifier.fit(X_train,Y_train)

RandomForestClassifier()

In [0]:
Y_pred=classifier.predict(X_test)

In [0]:
from sklearn.metrics import accuracy_score,classification_report

In [0]:
print(accuracy_score(Y_test,Y_pred))

0.9730700179533214


In [0]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.94      0.87      0.90       158
           1       0.98      0.99      0.98       956

    accuracy                           0.97      1114
   macro avg       0.96      0.93      0.94      1114
weighted avg       0.97      0.97      0.97      1114

