In [1]:
# need to troubleshoot

import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king=wv['king']

In [3]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [4]:
##import pandas as pd
## messages=pd.read_csv('/home/manan/jypyternotebook/NLP/spam.csv',  skiprows=[0], usecols=[0, 1], names=["label","message"])
import pandas as pd
messages=pd.read_csv('/home/manan/jypyternotebook/NLP/SMSSpamCollection.csv',
                    sep='\t',names=["label","message"])
messages.shape

(5572, 2)

In [5]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [6]:
type(messages)

pandas.core.frame.DataFrame

In [7]:
from nltk.stem import WordNetLemmatizer
lemmitizer=WordNetLemmatizer()

In [8]:
## Data cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')
import re
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ', messages['message'][i])
    review=review.lower()
    review=review.split()
    review = [lemmitizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
corpus[449]

'lol have you made plan for new year'

In [10]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [11]:
words=[]

In [12]:
# aletnative to using the above method to make corpus lowercae and splitting
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [13]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [14]:
import gensim
## lets train word2vec from scratch
model=gensim.models.Word2Vec(words)

In [15]:
# to get all the vocabulory 
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [16]:
model.corpus_count

5569

In [17]:
model.epochs

5

In [18]:
model.wv.similar_by_word('world')

[('no', 0.9990656971931458),
 ('had', 0.9990105032920837),
 ('any', 0.9990088939666748),
 ('try', 0.9990057349205017),
 ('over', 0.9989872574806213),
 ('amp', 0.9989773631095886),
 ('never', 0.9989712834358215),
 ('an', 0.9989537000656128),
 ('sent', 0.998941957950592),
 ('by', 0.9989253878593445)]

## Average word2vec

In [19]:
!pip install tqdm
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [20]:
from tqdm import tqdm

In [21]:
# apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|                                                                                                                          | 0/5569 [00:00<?, ?it/s]/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.9/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 7156.48it/s]


In [22]:
X[450]

array([-0.19116454,  0.33323333,  0.13311386,  0.03153685,  0.05105589,
       -0.73402345,  0.31984264,  0.6973034 , -0.36962253, -0.27441967,
       -0.23767594, -0.5932915 , -0.23047331,  0.0537716 ,  0.25645602,
       -0.21859697,  0.09600804, -0.39798844, -0.13149768, -0.7281532 ,
        0.18707094, -0.00903116,  0.12327456, -0.32230914, -0.00983866,
       -0.00989404, -0.32974458, -0.30119914, -0.41025588, -0.07590604,
        0.34696072,  0.01167095,  0.23561472, -0.3464934 , -0.1289673 ,
        0.4785792 ,  0.1544444 , -0.17862803, -0.24029717, -0.630548  ,
        0.00230832, -0.29909104, -0.24659386, -0.05299534,  0.27492374,
        0.00963131, -0.08270001, -0.04835531,  0.40889788,  0.22976771,
        0.21870682, -0.29745373, -0.04244287,  0.04581866, -0.1719673 ,
        0.07095509,  0.2686917 ,  0.12379206, -0.49654037,  0.21784821,
        0.03759924,  0.0741677 , -0.13326767, -0.21952263, -0.37051666,
        0.38780877,  0.04152183,  0.34692004, -0.47622   ,  0.51

In [25]:
len(X)

5569

In [27]:
X_new=np.array(X, dtype=object)

In [28]:
X_new.shape

(5569,)

In [30]:
# we are getting single number, not for 100 array dimension, check again
X_new[1]

array([-0.17911917,  0.18477519,  0.07764398,  0.02893274,  0.06852376,
       -0.4481476 ,  0.16266344,  0.44678813, -0.25091934, -0.14486285,
       -0.16908327, -0.36025587, -0.12212642,  0.03936481,  0.16790058,
       -0.14603902,  0.08720115, -0.27603367, -0.07812858, -0.4865147 ,
        0.12789732,  0.00833823,  0.11355227, -0.17609088, -0.01076774,
        0.01208142, -0.20427194, -0.22004972, -0.23860705, -0.0198247 ,
        0.24980043, -0.01580089,  0.11274557, -0.17931688, -0.09488018,
        0.30502784,  0.04011381, -0.09544258, -0.09213075, -0.40684617,
        0.04666825, -0.17762956, -0.14631332, -0.01121534,  0.14820617,
        0.01575764, -0.08281639, -0.02515234,  0.20446809,  0.12800358,
        0.13484728, -0.17299095,  0.01937078,  0.04098228, -0.09943622,
        0.0669248 ,  0.19102724,  0.09073822, -0.2996096 ,  0.1595986 ,
        0.04135941,  0.05991682, -0.07057501, -0.10295223, -0.23639129,
        0.20942573,  0.03660901,  0.22217382, -0.25874016,  0.31

In [31]:
X_new[1].shape


(100,)

In [34]:
Y.shape

NameError: name 'Y' is not defined