## About Dataset
Context
This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content
5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.
Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.

Acknowledgements
This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
- Any other interesting analysis
  
#### Best Practises
1. Preprocessing And Cleaning
2. Train Test Split
3. BOW,TFIDF,Word2vec
4. Train ML algorithms

# load the data

In [1]:

import pandas as pd
data=pd.read_csv('/home/manan/jypyternotebook/NLP/all_kindle_review.csv')

In [2]:
data

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000
...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000


In [3]:
data=data[['reviewText','rating']]
data.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4


In [4]:
# checking for missing values

In [5]:
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [6]:
## checking for unique values of rating and quantity of rating
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [7]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

## Preprocessing and cleaning

In [8]:

# positive review is 1 and negative 0
data['rating']=data['rating'].apply(lambda x:0 if x<3 else 1)

/tmp/ipykernel_17640/4116951836.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['rating']=data['rating'].apply(lambda x:0 if x<3 else 1)


In [9]:
data.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",1
1,Great short read. I didn't want to put it dow...,1
2,I'll start by saying this is the first of four...,1
3,Aggie is Angela Lansbury who carries pocketboo...,1
4,I did not expect this type of book to be in li...,1


In [10]:
df=data

In [11]:
df.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",1
1,Great short read. I didn't want to put it dow...,1
2,I'll start by saying this is the first of four...,1
3,Aggie is Angela Lansbury who carries pocketboo...,1
4,I did not expect this type of book to be in li...,1


In [12]:
## conversion of reviewText
df['reviewText']=df['reviewText'].str.lower()
df.head()

/tmp/ipykernel_17640/901810590.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()


,reviewText,rating
0,"jace rankin may be short, but he's nothing to ...",1
1,great short read. i didn't want to put it dow...,1
2,i'll start by saying this is the first of four...,1
3,aggie is angela lansbury who carries pocketboo...,1
4,i did not expect this type of book to be in li...,1


In [13]:
## clean the data and removing special characters using lambda
import re
df['reviewText']=df['reviewText'].apply(lambda x: re.sub('[^a-z A-Z 0-9-]+', '',x))
# 
# df.head()
## clean stopwords
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')] ))

## remove url
df['reviewText']=df['reviewText'].apply(lambda x:re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))

## remove html
from bs4 import BeautifulSoup
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

/tmp/ipykernel_17640/2516139424.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: re.sub('[^a-z A-Z 0-9-]+', '',x))
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/tmp/ipykernel_17640/2516139424.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')] ))
/tmp/ipykernel_17

In [14]:
df.head()

,reviewText,rating
0,jace rankin may short hes nothing mess man hau...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four books wasnt expect...,1
3,aggie angela lansbury carries pocketbooks inst...,1
4,expect type book library pleased find price right,1


In [15]:
## lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [16]:
# creating a function
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [17]:
# calling the function
df['reviewText']=df['reviewText'].apply(lambda x: lemmatize_words(x))

/tmp/ipykernel_17640/909382010.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: lemmatize_words(x))


In [18]:
df.head()

,reviewText,rating
0,jace rankin may short he nothing mess man haul...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four book wasnt expecti...,1
3,aggie angela lansbury carry pocketbook instead...,1
4,expect type book library pleased find price right,1


# Training Dataset

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(df['reviewText'], df['rating'], test_size= 0.20)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [23]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,Y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,Y_train)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [26]:
Y_pred_bow=nb_model_bow.predict(X_test_bow)
Y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)

In [27]:
print(accuracy_score(Y_test,Y_pred_bow))
print(accuracy_score(Y_test,Y_pred_tfidf))

0.57875
0.5766666666666667


In [28]:
print(classification_report(Y_test,Y_pred_bow))
print(classification_report(Y_test,Y_pred_tfidf))

              precision    recall  f1-score   support

           0       0.41      0.65      0.50       795
           1       0.76      0.54      0.63      1605

    accuracy                           0.58      2400
   macro avg       0.59      0.60      0.57      2400
weighted avg       0.64      0.58      0.59      2400

              precision    recall  f1-score   support

           0       0.41      0.63      0.50       795
           1       0.75      0.55      0.64      1605

    accuracy                           0.58      2400
   macro avg       0.58      0.59      0.57      2400
weighted avg       0.64      0.58      0.59      2400



In [29]:
confusion_matrix(Y_test,Y_pred_bow)

array([[515, 280],
       [731, 874]])

In [30]:
confusion_matrix(Y_test,Y_pred_tfidf)

array([[500, 295],
       [721, 884]])

In [31]:
## assignment try with Word2vec
from gensim.models import Word2Vec, KeyedVectors

In [32]:
# we start by creating vectorized words, split sentences into words arrays
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in df['reviewText']:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))



In [33]:
words[0]

['jace',
 'rankin',
 'may',
 'short',
 'he',
 'nothing',
 'mess',
 'man',
 'hauled',
 'saloon',
 'undertaker',
 'know',
 'he',
 'famous',
 'bounty',
 'hunter',
 'oregon',
 'shot',
 'man',
 'saloon',
 'finished',
 'year',
 'long',
 'quest',
 'avenge',
 'sister',
 'murder',
 'trying',
 'figure',
 'next',
 'snotty',
 'nosed',
 'farm',
 'boy',
 'rescued',
 'gang',
 'bully',
 'offer',
 'money',
 'kill',
 'man',
 'forced',
 'ranch',
 'reluctantly',
 'agrees',
 'bring',
 'man',
 'justice',
 'kill',
 'outright',
 'first',
 'need',
 'tell',
 'sister',
 'widower',
 'newskyla',
 'kyle',
 'springer',
 'bailey',
 'riding',
 'trail',
 'sleeping',
 'ground',
 'past',
 'month',
 'trying',
 'find',
 'jace',
 'want',
 'revenge',
 'man',
 'killed',
 'husband',
 'took',
 'ranch',
 'amongst',
 'crime',
 'shes',
 'keen',
 'detour',
 'jace',
 'want',
 'take',
 'realizes',
 'shes',
 'option',
 'hide',
 'behind',
 'boy',
 'persona',
 'best',
 'try',
 'keep',
 'pace',
 'confrontation',
 'along',
 'way',
 'get',

In [34]:
# now convert each sentence array into vectors with specific dimenstions
import gensim
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
model=gensim.models.Word2Vec(words)
# line below shows the list of word our model learnt embeddings for, sorting by most frequent to least
model.wv.index_to_key

['book',
 'story',
 'read',
 'one',
 'character',
 'like',
 'good',
 'would',
 'really',
 'love',
 'time',
 'get',
 'author',
 'reading',
 'series',
 'well',
 'much',
 'first',
 'even',
 'didnt',
 'short',
 'know',
 'way',
 'great',
 'could',
 'make',
 'sex',
 'little',
 'dont',
 'two',
 'thing',
 'want',
 'think',
 'find',
 'plot',
 'romance',
 'also',
 'end',
 'life',
 'im',
 'see',
 'enjoyed',
 'go',
 'scene',
 'never',
 'written',
 'take',
 'woman',
 'many',
 'lot',
 'kindle',
 'year',
 'say',
 'thought',
 'work',
 'bit',
 'found',
 'going',
 'give',
 'interesting',
 'liked',
 'writing',
 'novel',
 'loved',
 'another',
 'feel',
 'better',
 'got',
 'come',
 'man',
 'hot',
 'still',
 'back',
 'enough',
 'though',
 'people',
 'star',
 'reader',
 'made',
 'something',
 'review',
 'part',
 'friend',
 'cant',
 'page',
 'bad',
 'world',
 'need',
 'free',
 'new',
 'keep',
 'wasnt',
 'doesnt',
 'relationship',
 'enjoy',
 'recommend',
 'next',
 'together',
 'felt',
 'start',
 'best',
 'put',

In [35]:
model.wv.similar_by_word('book')

[('booki', 0.8068480491638184),
 ('sequel', 0.7848042845726013),
 ('others', 0.7837651371955872),
 ('reviewer', 0.7815616726875305),
 ('chapter', 0.7791232466697693),
 ('disappointed', 0.7762143611907959),
 ('bummed', 0.7761039733886719),
 ('trilogy', 0.7757830023765564),
 ('title', 0.7717628479003906),
 ('finished', 0.7672687768936157)]

## now convert to AVG word2vec

In [36]:
!pip install tqdm
from tqdm import tqdm
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 12000/12000 [00:27<00:00, 429.70it/s]


In [37]:
X[0]

array([-0.14958696,  0.23923948,  0.2756039 ,  0.10061634,  0.15622625,
       -0.38697895,  0.08825785,  0.6654355 , -0.19913349, -0.2124659 ,
       -0.3000304 , -0.2819015 , -0.07757779,  0.12245309,  0.04771583,
       -0.22111729,  0.13978069, -0.35756284,  0.02885783, -0.55377513,
       -0.02266204,  0.13401921,  0.2217056 , -0.18100028,  0.05977124,
        0.01020667, -0.29597318, -0.2009406 , -0.34269887,  0.06833102,
        0.2668851 ,  0.11417104,  0.14097774, -0.17377599, -0.1255908 ,
        0.46747532, -0.20196633, -0.4265702 ,  0.00810363, -0.5010442 ,
       -0.0896204 , -0.41494954, -0.18492313,  0.02058   ,  0.3088573 ,
       -0.13712853, -0.13126214, -0.13743299,  0.04094012,  0.06519112,
        0.29207203, -0.30158237, -0.0219453 ,  0.15317619, -0.31668264,
        0.22858003,  0.0479472 ,  0.03604625, -0.4267814 ,  0.15426077,
        0.12678723,  0.10229532, -0.08274763, -0.13023683, -0.24050361,
        0.5218178 ,  0.17901278,  0.2858562 , -0.30060455,  0.28

In [38]:
len(X)

12000

In [39]:
X_new=np.array(X, dtype=object)

In [40]:
X_new.shape

(12000, 100)

In [48]:
X[0].reshape(1,-1).shape


(1, 100)

In [50]:
df['rating'].shape

(12000,)

In [63]:
# now we will do a traintest split on X_new & df['rating']

In [64]:
X_train,X_test,Y_train,Y_test=train_test_split(X_new, df['rating'], test_size= 0.20)

In [65]:
X_train[0]

array([-0.14753004908561707, 0.6039883494377136, 0.16667932271957397,
       0.22327503561973572, 0.10809393227100372, -0.5873929262161255,
       0.30581724643707275, 0.7164880633354187, -0.20752382278442383,
       -0.7557116746902466, -0.374783456325531, -0.5972899198532104,
       0.033035438507795334, 0.20671093463897705, 0.39563268423080444,
       0.000401391094783321, 0.6101770997047424, -0.2649681270122528,
       -0.6494641304016113, -1.4902985095977783, -0.09587384015321732,
       0.27438998222351074, 0.577526867389679, -0.37352561950683594,
       -0.19902105629444122, 0.4604436457157135, -0.2879188656806946,
       -0.13734786212444305, -0.26689597964286804, 0.3510950207710266,
       0.3437901437282562, -0.10152574628591537, 0.6246665716171265,
       -0.6918972730636597, -0.7719772458076477, 0.7721149325370789,
       0.09456367790699005, 0.08824341744184494, -0.664212703704834,
       -0.2982402741909027, -0.20127496123313904, -0.03735286742448807,
       -0.1215331926

In [66]:
Y_train[0]

1

In [68]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
nb_model_avgw2v=GaussianNB().fit(X_train,Y_train)

In [69]:
Y_pred_avgw2v=nb_model_avgw2v.predict(X_test)

In [ ]:
print(accuracy_score(Y_test,Y_pred_avgw2v))

In [ ]:
confusion_matrix(Y_test,Y_pred_avgw2v)

In [ ]:
print(classification_report(Y_test,Y_pred_avgw2v))